### ISSUE TITLE
Sign the assembly with a strong name

### ISSUE THREAD

**Issue by PMoski** [Independer/wcfdataannotations#6]
Please, sign your assembly with a strong name to be usable in strong-named projects. I can't reference your NuGet package directly in my WCF library, I get the following error:

```
System.IO.FileLoadException: Could not load file or assembly 'Independer.WCFDataAnnotations, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
File name: 'Independer.WCFDataAnnotations, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null'
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.IsCustomAttributeDefined(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Int32 attributeCtorToken, Boolean mustBeInheritable)
   at System.Reflection.CustomAttribute.IsDefined(RuntimeType type, RuntimeType caType, Boolean inherit)
   at Microsoft.Tools.Common.ServiceReflectionUtility.HasServiceContractAttribute(Type type)
   at Microsoft.Tools.Common.ServiceReflectionUtility.IsWcfServiceClass(Type type)
   at Microsoft.Tools.SvcHost.ServiceHostHelper.CheckServiceKind(Type type)
   at Microsoft.Tools.SvcHost.ServiceHostHelper.LoadServiceAssembly(String svcAssemblyPath)
   at Microsoft.Tools.SvcHost.ServiceHostHelper.LoadServiceAssembly(String svcAssemblyPath)
   at Microsoft.Tools.SvcHost.CrossAppDomainSvcHost..ctor(String svcAssemblyPath, String svcConfigPath)
```

Thanks,
Moski

**Comment by istvan86-nagy** [comment]
Hi Moski,

thanks for your comment, I will look into this in the coming days.

Best Regards,
István

**Comment by PMoski** [comment]
Thank you very much @istvan86-nagy!
I'll try the signed version.

Best Regards,
Moski
